version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: emotion-island-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: emotion_island
      MYSQL_USER: emotion_user
      MYSQL_PASSWORD: emotion_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - emotion-network

  # 后端应用服务
  backend:
    build: .
    container_name: emotion-island-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emotion_island?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: emotion_user
      SPRING_DATASOURCE_PASSWORD: emotion_pass
    depends_on:
      - mysql
    networks:
      - emotion-network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:

networks:
  emotion-network:
    driver: bridge

